#!/bin/bash
# Menu Trojan - by znand-dev

# Warna
GREEN='\e[1;32m'
YELLOW='\e[1;33m'
CYAN='\e[1;36m'
NC='\e[0m'

clear
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}             ⚙️  MENU TROJAN XRAY              ${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}[1]${NC} Tambah Akun Trojan"
echo -e "${GREEN}[2]${NC} Hapus Akun Trojan"
echo -e "${GREEN}[3]${NC} Cek Login Trojan"
echo -e "${GREEN}[4]${NC} Perpanjang Masa Aktif Akun"
echo -e "${GREEN}[x]${NC} Kembali ke menu utama"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

read -p "👉 Pilih opsi: " opt

case $opt in
1) 
bash /etc/autoscriptvpn/xray/add-trojan.sh 
;;

2) 
bash /etc/autoscriptvpn/xray/del-trojan.sh 
;;

3)
bash /etc/autoscriptvpn/xray/cek-trojan.sh 
;;

4) 
bash /etc/autoscriptvpn/xray/renew-trojan.sh 
;;

x) 
menu 
;;
*) echo "❌ Pilihan salah!"
sleep 1
exec m-trojan
;;
esac
